spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/test_db}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
  packages-to-scan:
    - com.recruitment.casttest
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
server:
  port: ${SERVER_PORT:8080}

